include ../options.mk

SOURCES=$(wildcard *.cpp) $(wildcard ../models/*.cpp) $(wildcard ../views/*.cpp) $(wildcard ../lib/socket/*.cpp) ../lib/json/utils.cpp ../lib/json/json.cpp ../lib/file/files.cpp
OBJECTS=$(SOURCES:.cpp=.o)
HEADERS=$(wildcard *.h)
EXECUTABLE=server

include ../rules.mk