#include "Infirmary.h"

/*
 */



void Infirmary::heal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--741708:143053b354d:-8000:0000000000000B4D begin
{
}
// section 127-0-1-1--741708:143053b354d:-8000:0000000000000B4D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
