#include "Manager.h"




void Manager::getExperience()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B76 begin
{
}
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B76 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Manager::setExperience()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B78 begin
{
}
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B78 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
