#include "Match.h"




void Match::getScore()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2--79-32--746c2cb8:142d3a16a65:-8000:0000000000000937 begin
{
}
// section -87--2--79-32--746c2cb8:142d3a16a65:-8000:0000000000000937 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
