#include "NonFieldPlayer.h"




void NonFieldPlayer::getLevel()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-728a9697:142e2f43ac3:-8000:0000000000000B1B begin
{
}
// section 127-0-1-1-728a9697:142e2f43ac3:-8000:0000000000000B1B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void NonFieldPlayer::setExp()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-728a9697:142e2f43ac3:-8000:0000000000000B21 begin
{
}
// section 127-0-1-1-728a9697:142e2f43ac3:-8000:0000000000000B21 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void NonFieldPlayer::levelUp()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--741708:143053b354d:-8000:0000000000000B53 begin
{
}
// section 127-0-1-1--741708:143053b354d:-8000:0000000000000B53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void NonFieldPlayer::Vocation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B74 begin
{
}
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B74 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
