#include "Player.h"




void Player::getSpeed()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B6A begin
{
}
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B6A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Player::getForce()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B6C begin
{
}
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B6C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Player::getAgility()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B6E begin
{
}
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B6E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Player::getReflexes()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B70 begin
{
}
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B70 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Player::getPassPrecision()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B72 begin
{
}
// section 127-0-1-1-195549bb:1430b7a942f:-8000:0000000000000B72 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
