#include "Team.h"




void Team::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-663c1741:142f688f069:-8000:0000000000000B3D begin
{
}
// section 127-0-1-1-663c1741:142f688f069:-8000:0000000000000B3D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
