#define NAME "name"
#define USERNAME "username"
#define PASSWORD "password"
#define LEVEL "level"
#define MONEY "money"

enum {
    CODE_SUCCESS,
    CODE_BAD_PASSWORD,
    CODE_BAD_PASSWORD_FORMAT,
    CODE_ACCOUNT_NOT_FOUND,
    CODE_WRONG_MESSAGE_FORMAT,
    CODE_FAIL_TO_SAVE,
    CODE_ACCOUNT_ALREADY_EXIST,
    CODE_OCCUPED_USER
};