include ../options.mk

SOURCES=$(wildcard *.cpp) ../lib/socket/Socket.cpp ../models/NonFieldPlayer.cpp ../models/Player.cpp ../models/Item.cpp
OBJECTS=$(SOURCES:.cpp=.o)
HEADERS=$(wildcard *.h)
EXECUTABLE=client

include ../rules.mk
